flist = ['Adiac', 'ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'Car', 'CBF', 'ChlorineConcentration',
         'CinCECGTorso', 'Coffee', 'Computers', 'CricketX', 'CricketY', 'CricketZ', 'DiatomSizeReduction',
         'DistalPhalanxOutlineAgeGroup', 'DistalPhalanxOutlineCorrect', 'DistalPhalanxTW', 'Earthquakes', 'ECG200',
         'ECG5000', 'ECGFiveDays', 'ElectricDevices', 'FaceAll', 'FaceFour', 'FacesUCR', 'FiftyWords', 'Fish',
         'FordA', 'FordB', 'GunPoint', 'Ham', 'HandOutlines', 'Haptics', 'Herring', 'InlineSkate',
         'InsectWingbeatSound', 'ItalyPowerDemand', 'LargeKitchenAppliances', 'Lightning2', 'Lightning7', 'Mallat',
         'Meat', 'MedicalImages', 'MiddlePhalanxOutlineAgeGroup', 'MiddlePhalanxOutlineCorrect', 'MiddlePhalanxTW',
         'MoteStrain', 'NonInvasiveFetalECGThorax1', 'NonInvasiveFetalECGThorax2', 'OliveOil', 'OSULeaf',
         'PhalangesOutlinesCorrect', 'Phoneme', 'Plane', 'ProximalPhalanxOutlineAgeGroup',
         'ProximalPhalanxOutlineCorrect', 'ProximalPhalanxTW', 'RefrigerationDevices', 'ScreenType', 'ShapeletSim',
         'ShapesAll', 'SmallKitchenAppliances', 'SonyAIBORobotSurface1', 'SonyAIBORobotSurface2', 'StarLightCurves',
         'Strawberry', 'SwedishLeaf', 'Symbols', 'SyntheticControl', 'ToeSegmentation1', 'ToeSegmentation2',
         'Trace', 'TwoLeadECG', 'TwoPatterns', 'UWaveGestureLibraryAll', 'UWaveGestureLibraryX',
         'UWaveGestureLibraryY', 'UWaveGestureLibraryZ', 'Wafer', 'Wine', 'WordSynonyms', 'Worms', 'WormsTwoClass',
         'Yoga', 'ACSF1', 'AllGestureWiimoteX', 'AllGestureWiimoteY', 'AllGestureWiimoteZ', 'BME', 'Chinatown',
         'Crop', 'DodgerLoopDay', 'DodgerLoopGame', 'DodgerLoopWeekend', 'EOGHorizontalSignal', 'EOGVerticalSignal',
         'EthanolLevel', 'FreezerRegularTrain', 'FreezerSmallTrain', 'Fungi', 'GestureMidAirD1', 'GestureMidAirD2',
         'GestureMidAirD3', 'GesturePebbleZ1', 'GesturePebbleZ2', 'GunPointAgeSpan', 'GunPointMaleVersusFemale',
         'GunPointOldVersusYoung', 'HouseTwenty', 'InsectEPGRegularTrain', 'InsectEPGSmallTrain',
         'MelbournePedestrian', 'MixedShapesRegularTrain', 'MixedShapesSmallTrain', 'PickupGestureWiimoteZ',
         'PigAirwayPressure', 'PigArtPressure', 'PigCVP', 'PLAID', 'PowerCons', 'Rock', 'SemgHandGenderCh2',
         'SemgHandMovementCh2', 'SemgHandSubjectCh2', 'ShakeGestureWiimoteZ', 'SmoothSubspace', 'UMD']

multiflist =  ['ArticularyWordRecognition', 'AtrialFibrillation', 'BasicMotions', 'CharacterTrajectories', 'Cricket', 'DuckDuckGeese', 'EigenWorms', 'Epilepsy', 'EthanolConcentration', 'ERing', 'FaceDetection', 'FingerMovements', 'HandMovementDirection', 'Handwriting', 'Heartbeat', 'InsectWingbeat', 'JapaneseVowels', 'Libras', 'LSST', 'MotorImagery', 'NATOPS', 'PenDigits', 'PEMS-SF', 'PhonemeSpectra', 'RacketSports', 'SelfRegulationSCP1', 'SelfRegulationSCP2', 'SpokenArabicDigits', 'StandWalkJump', 'UWaveGestureLibrary']

resnet_config ={
    'Adiac': [0.5, 1.0],
    'ArrowHead': [0.5, 0.5],
    'Beef': [0.25, 0.25],
    'BeetleFly': [0.5, 1.0],
    'BirdChicken': [0.5, 1.0],
    'Car': [0.5, 1.0],
    'CBF': [0.5, 1.0],
    'ChlorineConcentration': [0.5, 1.0],
    'CinCECGTorso': [0.5, 1.0],
    'Coffee': [0.5, 1.0],
    'Computers': [0.5, 1.0],
    'CricketX': [0.5, 1.0],
    'CricketY': [0.5, 1.0],
    'CricketZ': [0.5, 1.0],
    'DiatomSizeReduction': [0.5, 1.0],
    'DistalPhalanxOutlineAgeGroup': [0.5, 0.25],
    'DistalPhalanxOutlineCorrect': [0.5, 1.0],
    'DistalPhalanxTW': [0.5, 1.0],
    'Earthquakes': [0.5, 1.0],
    'ECG200': [0.5, 1.0],
    'ECG5000': [0.5, 1.0],
    'ECGFiveDays': [0.5, 1.0],
    'ElectricDevices': [0.5, 1.0],
    'FaceAll': [0.5, 1.0],
    'FaceFour': [0.5, 1.0],
    'FacesUCR': [0.5, 1.0],
    'FiftyWords': [0.5, 1.0],
    'Fish': [0.5, 1.0],
    'FordA': [0.5, 1.0],
    'FordB': [0.5, 1.0],
    'GunPoint': [0.5, 1.0],
    'Ham': [0.5, 1.0],
    'HandOutlines': [0.5, 1.0],
    'Haptics': [0.5, 1.0],
    'Herring': [0.5, 1.0],
    'InlineSkate': [0.5, 1.0],
    'InsectWingbeatSound': [0.5, 1.0],
    'ItalyPowerDemand': [0.5, 1.0],
    'LargeKitchenAppliances': [0.5, 1.0],
    'Lightning2': [0.5, 1.0],
    'Lightning7': [0.5, 1.0],
    'Mallat': [0.5, 1.0],
    'Meat': [0.5, 1.0],
    'MedicalImages': [0.5, 1.0],
    'MiddlePhalanxOutlineAgeGroup': [0.5, 1.0],
    'MiddlePhalanxOutlineCorrect': [0.5, 1.0],
    'MiddlePhalanxTW': [0.5, 1.0],
    'MoteStrain': [0.5, 1.0],
    'NonInvasiveFetalECGThorax1': [0.5, 1.0],
    'NonInvasiveFetalECGThorax2': [0.5, 1.0],
    'OliveOil': [0.5, 1.0],
    'OSULeaf': [0.5, 1.0],
    'PhalangesOutlinesCorrect': [0.5, 1.0],
    'Phoneme': [0.5, 1.0],
    'Plane': [0.5, 1.0],
    'ProximalPhalanxOutlineAgeGroup': [0.5, 1.0],
    'ProximalPhalanxOutlineCorrect': [0.5, 1.0],
    'ProximalPhalanxTW': [0.5, 1.0],
    'RefrigerationDevices': [0.5, 1.0],
    'ScreenType': [0.5, 1.0],
    'ShapeletSim': [0.5, 1.0],
    'ShapesAll': [0.5, 1.0],
    'SmallKitchenAppliances': [0.5, 1.0],
    'SonyAIBORobotSurface1': [0.5, 1.0],
    'SonyAIBORobotSurface2': [0.5, 1.0],
    'StarLightCurves': [0.5, 1.0],
    'Strawberry': [0.5, 1.0],
    'SwedishLeaf': [0.5, 1.0],
    'Symbols': [0.5, 1.0],
    'SyntheticControl': [0.5, 1.0],
    'ToeSegmentation1': [0.5, 1.0],
    'ToeSegmentation2': [0.5, 1.0],
    'Trace': [0.5, 1.0],
    'TwoLeadECG': [0.5, 1.0],
    'TwoPatterns': [0.5, 1.0],
    'UWaveGestureLibraryAll': [0.5, 1.0],
    'UWaveGestureLibraryX': [0.5, 1.0],
    'UWaveGestureLibraryY': [0.5, 1.0],
    'UWaveGestureLibraryZ': [0.5, 1.0],
    'Wafer': [0.5, 1.0],
    'Wine': [0.5, 1.0],
    'WordSynonyms': [0.5, 1.0],
    'Worms': [0.5, 1.0],
    'WormsTwoClass': [0.5, 1.0],
    'Yoga': [0.5, 1.0],
    'ACSF1': [0.5, 1.0],
    'AllGestureWiimoteX': [0.5, 1.0],
    'AllGestureWiimoteY': [0.5, 1.0],
    'AllGestureWiimoteZ': [0.5, 1.0],
    'BME': [0.5, 1.0],
    'Chinatown': [0.5, 1.0],
    'Crop': [0.5, 1.0],
    'DodgerLoopDay': [0.5, 1.0],
    'DodgerLoopGame': [0.5, 1.0],
    'DodgerLoopWeekend': [0.5, 1.0],
    'EOGHorizontalSignal': [0.5, 1.0],
    'EOGVerticalSignal': [0.5, 1.0],
    'EthanolLevel': [0.5, 1.0],
    'FreezerRegularTrain': [0.5, 1.0],
    'FreezerSmallTrain': [0.5, 1.0],
    'Fungi': [0.5, 1.0],
    'GestureMidAirD1': [0.5, 1.0],
    'GestureMidAirD2': [0.5, 1.0],
    'GestureMidAirD3': [0.5, 1.0],
    'GesturePebbleZ1': [0.5, 1.0],
    'GesturePebbleZ2': [0.5, 1.0],
    'GunPointAgeSpan': [0.5, 1.0],
    'GunPointMaleVersusFemale': [0.5, 1.0],
    'GunPointOldVersusYoung': [0.5, 1.0],
    'HouseTwenty': [0.5, 1.0],
    'InsectEPGRegularTrain': [0.5, 1.0],
    'InsectEPGSmallTrain': [0.5, 1.0],
    'MelbournePedestrian': [0.5, 1.0],
    'MixedShapesRegularTrain': [0.5, 1.0],
    'MixedShapesSmallTrain': [0.5, 1.0],
    'PickupGestureWiimoteZ': [0.5, 1.0],
    'PigAirwayPressure': [0.5, 1.0],
    'PigArtPressure': [0.5, 1.0],
    'PigCVP': [0.5, 1.0],
    'PLAID': [0.5, 1.0],
    'PowerCons': [0.5, 1.0],
    'Rock': [0.5, 1.0],
    'SemgHandGenderCh2': [0.5, 1.0],
    'SemgHandMovementCh2': [0.5, 1.0],
    'SemgHandSubjectCh2': [0.5, 1.0],
    'ShakeGestureWiimoteZ': [0.5, 1.0],
    'SmoothSubspace': [0.5, 1.0],
    'UMD': [0.5, 1.0]}